#!/bin/bash

start=$(pwd)

cd ../template

tckgen -angle 22.5 -maxlen 250 -minlen 10 -power 1.0 wmfod_template.mif \
-seed_image template_mask.mif -mask template_mask.mif -select 20000000 \
-cutoff 0.10 tracks_20_million.tck

tcksift -force tracks_20_million.tck wmfod_template.mif \
tracks_2_million_sift.tck -term_number 2000000
