#!/bin/bash

start=$(pwd)

for dir in $(ls -d mind[oy]???) ; do
	cd $dir
 	dwiextract dwi_biascorrected_normalised_upsampled.mif  b0_preproc_bias.nii -bzero
    	mrcalc aseg.mgz 41 -eq aseg.mgz 2 -eq -add wm.nii
	mrconvert nu.mgz nu.nii
	mrconvert brain.mgz brain.nii
	epi_reg --epi=b0_preproc_bias.nii --t1=nu.nii --t1brain=brain.nii --out=epi2struct --wmseg=wm.nii
	transformconvert epi2struct.mat b0_preproc_bias.nii nu.nii flirt_import epi2struct_mrtrix.mat
	mrtransform nu.nii --linear epi2struct_mrtrix.mat nu_dMRIreg.nii -inverse
	5ttgen -force fsl nu_dMRIreg.nii 5tt.mif -nocrop
	cd $start

mkdir ./young
mkdir ./old 

for dir in $(ls -d mind[o]???) ; do
	cd $dir
 	cp nu_dMRIreg.nii ../old/PRE.mif
	cd $start

for dir in $(ls -d mind[y]???) ; do
	cd $dir
 	cp nu_dMRIreg.nii ../young/PRE.mif
	cd $start


mrmath ./old/* mean Old_T1.miff
5ttgen fsl Old_T1.mif Old_5tt.mif -nocrop
mrconvert -coord 3 3 Old_5tt.mif Old_5tt_3.mif
mrthreshold -abs 0.1 -invert Old_5tt_3.mif t1oldCSF.mif

mrmath ./young/* mean Young_T1.miff
5ttgen fsl Young_T1.mif Young_5tt.mif -nocrop
mrconvert -coord 3 3 Young_5tt.mif Young_5tt_3.mif
mrthreshold -abs 0.1 -invert Young_5tt_3.mif t1youngCSF.mif


mrmath t1oldCSF.mif t1youngCSF.mif min ../template/CSFmask.mif
Voxel2fixel ../template/fixel_mask/ ../template/ CSFmask_fixel.mif 

rm -r ./young
rm -r ./old
rm Old_T1.mif
rm Old_5tt.mif
rm Old_5tt_3.mif
rm t1oldCSF.mif
rm Young_T1.mif
rm Young_5tt.mif
rm Young_5tt_3.mif
rm t1youngCSF.mif



