#!/bin/bash

start=$(pwd)

for dir in $(ls -d mind[oy]???) ; do
    cd $dir
    dwi2mask dwi.mif dwi_temp_mask.mif
    dwibiascorrect -ants dwi.mif dwi_biascorrected_fba.mif
    cd $start
done

for dir in $(ls -d mind[oy]???) ; do
	cd $dir
	ln -sr dwi_biascorrected_fba.mif ../../dwiintensitynorm/dwi_input/$dir.mif
	ln -sr dwi_temp_mask.mif ../../dwiintensitynorm/mask_input/$dir.mif
	cd $start
done

dwiintensitynorm ../dwiintensitynorm/dwi_input/ \
 ../dwiintensitynorm/mask_input/ \
../dwiintensitynorm/dwi_output/ ../dwiintensitynorm/fa_template.mif \
../dwiintensitynorm/fa_template_wm_mask.mif

for dir in $(ls -d mind[oy]???) ; do
	 cd $dir
	 ln -sr ../../dwiintensitynorm/dwi_output/$dir.mif \
	 dwi_biascorrected_fba_normalised.mif
	 dwi2response tournier dwi_biascorrected_fba_normalised.mif \
	 response_fba.txt
	 cd $start
 done

average_response */response_fba.txt ../group_average_response.txt

for dir in $(ls -d mind[oy]???); do
	cd $dir
	mrresize dwi_biascorrected_fba_normalised.mif -vox 1.3 \
	dwi_biascorrected_normalised_upsampled.mif
        dwi2mask dwi_biascorrected_normalised_upsampled.mif \
        dwi_mask_upsampled.mif
        dwiextract dwi_biascorrected_normalised_upsampled.mif - \
	| dwi2fod csd - ../../group_average_response.txt wmfod.mif -mask dwi_mask_upsampled.mif
        cd $start
done

mkdir -p ../template/fod_input
mkdir ../template/mask_input

for dir in $(ls -d mind[oy]???) ; do
        cd $dir
        ln -sr wmfod.mif ../../template/fod_input/$dir.mif
        ln -sr dwi_mask_upsampled.mif ../../template/mask_input/$dir.mif
        cd $start
done
