%Get mean individual FDC values for each tract.

fdc = [];

tracts = {'Cingulum_ret/L_fdcvalues.txt', ...
'Cingulum_ret/R_fdcvalues.txt', ...
'Cingulum_sub/L_sub_fdcvalues.txt', ...
'Cingulum_sub/R_sub_fdcvalues.txt', ...
'Cingulum_para/L_para_fdcvalues.txt', ...
'Cingulum_para/R_para_fdcvalues.txt', ...
'Cingulum_para/L_para_pari_fdcvalues.txt', ...
'Cingulum_para/R_para_pari_fdcvalues.txt', ...
'Cingulum_para/L_para_temp_fdcvalues.txt', ...
'Cingulum_para/R_para_temp_fdcvalues.txt', ...
'Corticospinal/L_fdcvalues.txt', ...
'Corticospinal/R_fdcvalues.txt', ...
'Corticospinal/L_inf_fdcvalues.txt', ...
'Corticospinal/R_inf_fdcvalues.txt', ...
'Corticospinal/L_sup_fdcvalues.txt', ...
'Corticospinal/R_sup_fdcvalues.txt', ...
'Forceps_major/fdcvalues.txt', ...
'Forceps_minor/fdcvalues.txt', ...
'Fornix/fdcvalues.txt', ...
'IFO/L_fdcvalues.txt', ...
'IFO/R_fdcvalues.txt', ...
'ILF/L_fdcvalues.txt', ...
'ILF/R_fdcvalues.txt', ...
'Internal_capsule/L_fdcvalues.txt', ...
'Internal_capsule/R_fdcvalues.txt', ...
'SLF1/L_fdcvalues.txt', ...
'SLF1/R_fdcvalues.txt', ...
'SLF2/L_fdcvalues.txt', ...
'SLF2/R_fdcvalues.txt', ...
'SLF3/L_fdcvalues.txt', ...
'SLF3/R_fdcvalues.txt', ...
'Uncinate_fasciculus/L_fdcvalues.txt' ...
'Uncinate_fasciculus/R_fdcvalues.txt'};

cd Tracts/

for i = 1:length(tracts);
nums = importdata(tracts{i});
fdc = [fdc nums];
end

fdctab = array2table(fdc');


variablenames = {'L_Cing_ret'
	'R_Cing_ret'
	'L_Cing_sub'
	'R_Cing_sub'
	'L_Cing_para'
	'R_Cing_para'
	'L_Cing_para_P'
	'R_Cing_para_P'
	'L_Cing_para_T'
	'R_Cing_para_T'
	'L_Corticospinal'
	'R_Corticospinal'
	'L_Corticospinal_Inf'
	'R_Corticospinal_Inf'
	'L_Corticospinal_Sup'
	'R_Corticospinal_Sup'
	'Forceps_major'
	'Forceps_minor'
	'Fornix'
	'L_IFO'
	'R_IFO'
	'L_ILF'
	'R_ILF'
	'L_Internal_capsule'
	'R_Internal_capsule'
	'L_SLF1'
	'R_SLF1'
	'L_SLF'
	'R_SLF'
	'L_SLF3'
	'R_SLF3'
	'L_Uncinate_fasciculus'
	'R_Uncinate_fasciculus'};

fdctab.Properties.RowNames = variablenames;
writetable(fdctab, 'TSA/Outputs/fdcvalues.csv', 'WriteRowNames', true);
