mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_ret/R_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_ret/R_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_sub/R_sub_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_sub/R_sub_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/R_para_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/R_para_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/R_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/R_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Forceps_major/fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Forceps_major/fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Forceps_minor/fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Forceps_minor/fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Fornix/fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Fornix/fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/IFO/R_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/IFO/R_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/ILF/R_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/ILF/R_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Internal_capsule/R_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Internal_capsule/R_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF1/R_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF1/R_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF2/R_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF2/R_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF3/R_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF3/R_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Uncinate_fasciculus/R_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Uncinate_fasciculus/R_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_ret/L_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_ret/L_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_sub/L_sub_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_sub/L_sub_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/L_para_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/L_para_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/L_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/L_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/IFO/L_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/IFO/L_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/ILF/L_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/ILF/L_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Internal_capsule/L_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Internal_capsule/L_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF1/L_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF1/L_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF2/L_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF2/L_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF3/L_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/SLF3/L_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Uncinate_fasciculus/L_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Uncinate_fasciculus/L_fa_track2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/R_inf_fa.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/R_inf_fa2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/L_inf_fa.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/L_inf_fa2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/R_sup_fa.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/R_sup_fa2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/L_sup_fa.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Corticospinal/L_sup_fa2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/R_para_temp_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/R_para_temp2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/L_para_temp_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/L_para_temp2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/R_para_pari_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/R_para_pari2.mif -force
mrcalc /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/L_para_pari_fa_track.mif /nfs/tpolk/mind/Shannon/TSA/PVE/csfmask.mif -mult /nfs/tpolk/mind/Shannon/TSA/Tracts/Cingulum_para/L_para_pari2.mif -force
